name: geospatial-analysis-dev
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - numpy
  - act-atmos
  - scipy
  - xarray
  - matplotlib
  - netcdf4
  - pillow
  - holoviews
  - hvplot
  - bokeh
  - numpy
  - mystmd
  - metpy
  - pip
  - pip:
    - sage-data-client
    - ambient-api
    - windrose
    - sage-data-client
    - nexradaws
    - git+https://github.com/mgcarre/PythonMETAR
