name: geospatial-analysis-dev
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - xarray
  - matplotlib
  - netcdf4
  - pillow
  - metpy
  - numpy
  - mystmd
  - pip
  - pip:
    - sage-data-client
    - ambient-api